# Generated by Django 5.1.3 on 2024-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('register_no', models.CharField(max_length=9)),
                ('roll_no', models.CharField(max_length=9)),
                ('department', models.CharField(default='ComputerScience', max_length=100)),
                ('batch', models.CharField(default='2022-25', max_length=15)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
