# Generated by Django 5.1.3 on 2024-12-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VOTING', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_no',
            field=models.CharField(max_length=13),
        ),
    ]
