# Generated by Django 5.1.3 on 2025-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VOTING', '0002_alter_student_register_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(default='ComputerScience', max_length=100)),
                ('batch', models.CharField(default='2022-25', max_length=15)),
                ('image', models.ImageField(upload_to='profilepic/')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
